[program:freeternity.com]
command=node /home/freeternity/web/index.js
directory=/home/freeternity/web/
numprocs=1
process_name=%(program_name)s
autostart=true
autorestart=true
stderr_logfile=/home/freeternity/logs/err.log
stdout_logfile=/home/freeternity/logs/out.log
user=freeternity