[program:freeternity.com.normalizeNewsTimestamps]
command=node /home/freeternity/web/src/updateNewsTimestamps.js
directory=/home/freeternity/web/src/
autostart=true
autorestart=true
stderr_logfile=/home/freeternity/logs/normalizeNews.err.log
stdout_logfile=/home/freeternity/logs/normalizeNews.out.log
user=freeternity
