[program:freeternity.com.garbageCollect]
command=node /home/freeternity/web/src/garbageCollect.js
directory=/home/freeternity/web/src/
autostart=true
autorestart=true
stderr_logfile=/home/freeternity/logs/garbageCollect.err.log
stdout_logfile=/home/freeternity/logs/garbageCollect.out.log
user=freeternity
environment=GC_MONTHS="9",GC_INTERVAL_MS="3600000",GC_REQUEST_TIMEOUT_MS="45000",GC_BATCH_SIZE="100",GC_MAX_DOCS_PER_CYCLE="300"
