[program:freeternity.com.load_balance]
command=node /home/freeternity/web/load_balance.js
directory=/home/freeternity/web/
numprocs=1
process_name=%(program_name)s
autostart=true
autorestart=true
environment=WEB_PORTS="3001,3002"
stderr_logfile=/home/freeternity/logs/load_balance.err.log
stdout_logfile=/home/freeternity/logs/load_balance.out.log
user=freeternity
